### ISSUE TITLE
这个不支持qq 聊天?

### ISSUE THREAD

**Issue by ahuigo** [gera2ld/qqlib#10]
从这个角度说, 应该叫qZoneLib 吧?

**Comment by gera2ld** [comment]
这个库主要是实现qq的web登录，腾讯的登录是相通的，而且这个库最初分析的是webqq的协议，所以就叫qqlib了。

**Comment by ahuigo** [comment]
你可能理解错了, webqq 已经下线了,  现在走http协议聊天的只有smart qq了, smart qq的登录只能靠二维码登录, 和腾讯传统的登录是不相通的
