### ISSUE TITLE
发说说似乎失效了

### ISSUE THREAD

**Issue by sssir** [gera2ld/qqlib#12]

**Comment by gera2ld** [comment]
我测试是正常的，请提供更详细的信息

**Comment by sssir** [comment]
真是抱歉打扰您了，我是直接使用README给出的代码，运行没有报错，也显示了我的QQ昵称，可说说却没有发出来，请问我是否遗漏了哪些东西呢？谢谢

**Comment by sssir** [comment]
我找到原因了，少了一条 qq.login()

**Comment by gera2ld** [comment]
好吧，README确实写得不够明显，等下再改一下

**Comment by gera2ld** [comment]
好吧，README确实写得不够明显，等下再改一下
