### ISSUE TITLE
大神这个QQ空间密码加密算法怎么找的

### ISSUE THREAD

**Issue by DrKyro** [gera2ld/qqlib#16]
我想学学- -，网上都没有教程- -

**Comment by gera2ld** [comment]
web qq或者网页版qq空间登录页面的JS里有

**Comment by DrKyro** [comment]
问题就是不知道怎么找- -

**Comment by gera2ld** [comment]
用Chrome的开发者工具，把JS代码顺着执行顺序读一遍，可以通过断点找关键代码。。这是个苦力活:sweat_smile:

**Comment by DrKyro** [comment]
也是断点调试- -看变量啥时候变就是哪段在读- -
