### ISSUE TITLE
登陆进去后执行qq.feed()好像没有任何效果……

### ISSUE THREAD

**Issue by zxj5470** [gera2ld/qqlib#19]
真的有发说说的功能吗……

**Comment by gera2ld** [comment]
我这边测试是没有问题的，请自行验证。

另外提issue请说明具体问题。

**Comment by zxj5470** [comment]
文件 t.py
(环境：python3.6.0)
文件内容
def login(qq):
以及后面的登陆部分
qq=qzone.QZone(id,'password')
login(qq)
qq.feed('2333333333')


然后执行完了再执行
python -m unittest，得到的执行了是五个，说明之前执行过了，但是说说上没有看到相应内容。


D:\git\qqlib>python t.py

D:\git\qqlib>python -m unittest
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
