### ISSUE TITLE
AttributeError: Verifier instance has no attribute 'image'

### ISSUE THREAD

**Issue by tianjyan** [gera2ld/qqlib#20]
有用户在我的Repo上开了一个issue([Qzone_Photo/issues/7](https://github.com/youngytj/Qzone_Photo/issues/7))，是关于登录失败的，因为我是用了你的lib，能帮我解答一下这种错误会产生的场景吗？

**Comment by gera2ld** [comment]
1.1.0把验证码的获取机制变了一下，应该写成：
``` python
open('verify.jpg', 'wb').write(verifier.fetch_image())
```
感觉应该去releases里写一下breaking changes。。。

**Comment by tianjyan** [comment]
Agree with the breaking changes
