### ISSUE TITLE
抓取时出现错误。

### ISSUE THREAD

**Issue by 15814** [gera2ld/qqlib#26]
/lib/python3.6/site-packages/qq/__init__.py", line 43, in __init__
    self.login()
/lib/python3.6/site-packages/qq/__init__.py", line 70, in login
    return api.get_qr()
lib/python3.6/site-packages/qq/src/api.py", line 174, in get_qr
    os.startfile(tmp[1])
AttributeError: module 'os' has no attribute 'startfile'

**Comment by gera2ld** [comment]
这明显不是qqlib。。

**Comment by 15814** [comment]
查了下 应该是调用的不同，Windows 下用os.startfile(tmp[1])，但换到OS X就不行了。
