### ISSUE TITLE
可以二次访问增加一些cookies

### ISSUE THREAD

**Issue by jaguo** [gera2ld/qqlib#5]
self.nick = r[5]
self.fetch(r[2])

p_skey，p_uin，pt4_token for QZone

**Comment by gera2ld** [comment]
这个有必要吗？只能在这里获取吗？

**Comment by jaguo** [comment]
发表说说，点赞，空间留言的话需要这些cookies

**Comment by gera2ld** [comment]
有道理，看来那个`proxy_url`还是需要根据不同的服务来设置，现在是写死的qzone。。

**Comment by jaguo** [comment]
嗯嗯，不同的服务那个地址是不一样的
